spring:
  profiles:
    active: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/senior_transit_db
    username: root
    password: mjy51880256!

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      location: ${java.io.tmpdir}


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # .env ?? ????? ?? ??
      chat:
        options:
          model: gpt-4o
          temperature: 0.7

server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web.multipart: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

